# Default parameters for the dhf_localization_node.
# For the documentation of the parameters, see
# `dhf_localization_node.py`.

# ROS-specific
scan_topic: "/scan"
odom_topic: "/odom"
static_map_srv: "static_map"
robot_base_frame: "base_footprint"
odom_frame: "odom"
scan_frame: "base_scan"
global_frame: "map"
transform_tolerance: 0.1
detection_tolerance: 0.05

# Filter-specific
particles: 100
pseudo_timesteps: 10

# Measurement model
max_ray_number: 500
laser_range_noise_std: 0.01

# Motion model
odometry_alpha_1: 0.1
odometry_alpha_2: 0.1
odometry_alpha_3: 0.1
odometry_alpha_4: 0.1

# Initialization
initial_pose_x: -3.0
initial_pose_y: 1.0
initial_pose_heading: 0
initial_cov_x: 0.01
initial_cov_y: 0.01
initial_cov_heading: 0.0025

# Other
export_data: False




